# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "decisiontree"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ilya Grigorik"]
  s.date = "2013-02-21"
  s.description = "ID3-based implementation of the M.L. Decision Tree algorithm"
  s.email = "ilya@igvita.com"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "decisiontree.gemspec",
    "examples/continuous-id3.rb",
    "examples/data/continuous-test.txt",
    "examples/data/continuous-training.txt",
    "examples/data/discrete-test.txt",
    "examples/data/discrete-training.txt",
    "examples/discrete-id3.rb",
    "examples/simple.rb",
    "lib/decisiontree.rb",
    "lib/decisiontree/id3_tree.rb",
    "test/helper.rb",
    "test/test_decisiontree.rb"
  ]
  s.homepage = "http://github.com/igrigorik/decisiontree"
  s.require_paths = ["lib"]
  s.rubyforge_project = "decisiontree"
  s.rubygems_version = "1.8.24"
  s.summary = "ID3-based implementation of the M.L. Decision Tree algorithm"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

